# Generated by Django 4.2.11 on 2025-01-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libitem',
            fields=[
                ('id', models.CharField(db_column='Id', max_length=32, primary_key=True, serialize=False)),
                ('creationtime', models.DateTimeField(db_column='CreationTime')),
                ('creatoruserid', models.BigIntegerField(blank=True, db_column='CreatorUserId', null=True)),
                ('lastmodificationtime', models.DateTimeField(blank=True, db_column='LastModificationTime', null=True)),
                ('lastmodifieruserid', models.BigIntegerField(blank=True, db_column='LastModifierUserId', null=True)),
                ('isdeleted', models.BooleanField(db_column='IsDeleted')),
                ('deleteruserid', models.BigIntegerField(blank=True, db_column='DeleterUserId', null=True)),
                ('deletiontime', models.DateTimeField(blank=True, db_column='DeletionTime', null=True)),
                ('infoid', models.CharField(blank=True, db_column='InfoId', max_length=32, null=True)),
                ('title', models.CharField(db_column='Title', max_length=256)),
                ('author', models.CharField(blank=True, db_column='Author', max_length=256, null=True)),
                ('barcode', models.CharField(db_column='Barcode', max_length=32)),
                ('isenable', models.BooleanField(db_column='IsEnable')),
                ('callno', models.CharField(blank=True, db_column='CallNo', max_length=64, null=True)),
                ('precallno', models.CharField(blank=True, db_column='PreCallNo', max_length=64, null=True)),
                ('catalogcode', models.CharField(blank=True, db_column='CatalogCode', max_length=32, null=True)),
                ('itemstate', models.PositiveIntegerField(db_column='ItemState')),
                ('pressmarkid', models.CharField(blank=True, db_column='PressmarkId', max_length=32, null=True)),
                ('pressmarkname', models.CharField(blank=True, db_column='PressmarkName', max_length=64, null=True)),
                ('locationid', models.CharField(blank=True, db_column='LocationId', max_length=32, null=True)),
                ('locationname', models.CharField(blank=True, db_column='LocationName', max_length=128, null=True)),
                ('bookbarcode', models.CharField(blank=True, db_column='BookBarcode', max_length=32, null=True)),
                ('isbn', models.CharField(blank=True, db_column='ISBN', max_length=32, null=True)),
                ('pubno', models.SmallIntegerField(blank=True, db_column='PubNo', null=True)),
                ('publisher', models.CharField(blank=True, db_column='Publisher', max_length=512, null=True)),
                ('pubdate', models.CharField(blank=True, db_column='PubDate', max_length=32, null=True)),
                ('price', models.CharField(blank=True, db_column='Price', max_length=32, null=True)),
                ('pages', models.CharField(blank=True, db_column='Pages', max_length=32, null=True)),
                ('summary', models.TextField(blank=True, db_column='Summary', null=True)),
                ('itemtype', models.PositiveIntegerField(db_column='ItemType')),
                ('remark', models.CharField(blank=True, db_column='Remark', max_length=256, null=True)),
                ('origintype', models.PositiveIntegerField(db_column='OriginType')),
                ('createtype', models.PositiveIntegerField(db_column='CreateType')),
                ('tenantid', models.IntegerField(db_column='TenantId')),
            ],
            options={
                'verbose_name': '终端',
                'verbose_name_plural': '终端',
                'db_table': 'libitem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sysmenu',
            fields=[
                ('id', models.CharField(db_column='Id', max_length=32, primary_key=True, serialize=False)),
                ('creationtime', models.DateTimeField(blank=True, db_column='CreationTime', null=True)),
                ('creatoruserid', models.BigIntegerField(blank=True, db_column='CreatorUserId', null=True)),
                ('lastmodificationtime', models.DateTimeField(blank=True, db_column='LastModificationTime', null=True)),
                ('lastmodifieruserid', models.BigIntegerField(blank=True, db_column='LastModifierUserId', null=True)),
                ('isdeleted', models.BooleanField(db_column='IsDeleted')),
                ('deleteruserid', models.BigIntegerField(blank=True, db_column='DeleterUserId', null=True)),
                ('deletiontime', models.DateTimeField(blank=True, db_column='DeletionTime', null=True)),
                ('code', models.CharField(db_column='Code', max_length=32)),
                ('name', models.CharField(db_column='Name', max_length=32)),
                ('permissionname', models.CharField(blank=True, db_column='PermissionName', max_length=64, null=True)),
                ('icon', models.TextField(blank=True, db_column='Icon', null=True)),
                ('route', models.CharField(blank=True, db_column='Route', max_length=128, null=True)),
                ('parameters', models.CharField(blank=True, db_column='Parameters', max_length=128, null=True)),
                ('featuredependency', models.CharField(blank=True, db_column='FeatureDependency', max_length=64, null=True)),
                ('isexternal', models.BooleanField(db_column='IsExternal')),
                ('isiframe', models.BooleanField(db_column='IsIframe')),
                ('isauthenticate', models.BooleanField(db_column='IsAuthenticate')),
                ('sortcode', models.IntegerField(db_column='SortCode')),
                ('isenable', models.BooleanField(db_column='IsEnable')),
                ('parentid', models.CharField(blank=True, db_column='ParentId', max_length=32, null=True)),
                ('remark', models.CharField(blank=True, db_column='Remark', max_length=256, null=True)),
                ('systemtype', models.PositiveIntegerField(db_column='SystemType')),
                ('tenantid', models.IntegerField(blank=True, db_column='TenantId', null=True)),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
                'db_table': 'sysmenu',
                'managed': False,
            },
        ),
    ]
